name: Codecov
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 可以手动触发将测试覆盖率上传 https://about.codecov.io/
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set pnpm Version
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Run tests and collect coverage
        run: pnpm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
